Raphtory/docbrown

- docbrown/core/Cargo.toml
fix cargo.toml in core to include serde features
> fix building core only

- .gitignore
- docbrown/core/benches/tgraph_benchmarks.rs
- docbrown/core/src/adj.rs
- docbrown/core/src/bitset.rs
- docbrown/core/src/graph.rs
- docbrown/core/src/lib.rs
- docbrown/core/src/lsm.rs
- docbrown/core/src/misc.rs
- docbrown/core/src/props.rs
- docbrown/core/src/sorted_vec_map.rs
- docbrown/core/src/tadjset.rs
- docbrown/core/src/tcell.rs
- docbrown/core/src/tpartition.rs
- docbrown/core/src/tprop.rs
- docbrown/core/src/tpropvec.rs
- docbrown/db/src/lib.rs
- docbrown/db/src/main.rs
Bunch of refactoring and unit tests for properties models
> refactor docbrown

- docbrown/core/Cargo.toml
- docbrown/core/src/eval.rs
- docbrown/core/src/lib.rs
- docbrown/core/src/tgraph.rs
- docbrown/db/src/graph.rs
This is the first take on running an algorithm over `TemporalGraph`
this is not implemented for `db:Graph` yet as it needs allow for sync step across evaluations.
> Eval algo runner

- pyraphtory/src/graph_window.rs
- pyraphtory/src/wrappers.rs
Implements recursive exploration of neighbours from the Python API
> implement neighbourhood exploration iterables from python

- pyraphtory/src/graph_window.rs
- pyraphtory/src/wrappers.rs
- Add support for degree on the iterators
- Fix the flat-mapping over vertices when starting from `view.vertices()`
> More Python API's for WindowedView

- pyraphtory/src/graph_window.rs
> fix renamed id

- docbrown/db/src/algorithms.rs
- docbrown/db/src/algorithms/degree.rs
- docbrown/db/src/algorithms/directed_graph_density.rs
- raphtory/src/algorithms.rs
- raphtory/src/lib.rs
- raphtory/tests/test_graphdb.py
1. graph density algo
2. in/out min/max degree and average degree
> moar algos

- examples/rust/src/bin/btc/main.rs
- examples/rust/src/bin/hulongbay/main.rs
- examples/rust/src/bin/lotr/main.rs
update examples such that they work with the new api changes
examples no longer compiled
no
it compiles
Maybe we should be testing this in the CI?
> fix examples for view_api changes

- docbrown/core/src/lazy_vec.rs
- docbrown/core/src/lib.rs
- docbrown/core/src/props.rs
- docbrown/core/src/tgraph.rs
- docbrown/core/src/tgraph_shard.rs
- docbrown/db/src/graph.rs
- raphtory/Cargo.toml
- raphtory/src/graph.rs
- raphtory/tests/test_graphdb.py
> fix static id bug and improve error handling

- docbrown/db/src/graph_window.rs
- docbrown/db/src/perspective.rs
- docbrown/db/src/program.rs
- docbrown/db/src/vertex.rs
> Docs: Perspective, Program, Vertex

- docbrown/db/src/perspective.rs
> remove macos std

- python/src/graph_view.rs
- python/src/vertex.rs
> make vertices optionally act like an attribute

- docbrown/core/src/tgraph.rs
> change key to name

- .github/workflows/code_coverage.yml
> bug with cov report

- docbrown/src/db/edge.rs
- docbrown/src/db/vertex.rs
- python/src/edge.rs
- python/tests/test_graphdb.py
Time APIs for edges
Time APIs were missing
Yes
Test included
No
> Edge time ops

- .github/workflows/test_python_workflow.yml
- examples/py/nft/nft_analysis.ipynb
- examples/py/nft/nft_helper.py
- python/src/edge.rs
> NFT Example rewritten

- python/pyproject.toml
> Python Optional Deps

- Cargo.lock
> security update

- docbrown/src/algorithms/pagerank.rs
- docbrown/src/core/agg.rs
- docbrown/src/core/state.rs
- docbrown/src/core/utils.rs
- docbrown/src/db/program.rs
changes into program.rs to make it behave better on multiple shards
No
tests
yes many, program.rs is a mess
> Dev 1620 fix page rank

- python/src/algorithms.rs
- python/src/graph_view.rs
- python/tests/test_graphdb.py
> Change algorithms to use string or id
